### ISSUE TITLE
Paginação

### ISSUE THREAD

**Issue by Wenderson-Oscar** [Wenderson-Oscar/Livraria#1]
A opção de mostrar os livros na próxima página, não funciona. 📑

**Comment by Wenderson-Oscar** [comment]
resolvido

**Comment by Felipe-Moreira-Sa** [comment]
Não consigo encontrar meu mangás

**Comment by Wenderson-Oscar** [comment]
Atualmente não existe uma Scan disponível para registrar um mangás.
